services:

  airflow:

    build: .

    container_name: industrial-iot-airflow

    ports:
      - "8081:8080"

    environment:

      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://iot_user:iot_password@host.docker.internal:5433/airflow_metadata

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__API__SECRET_KEY: industrial-iot-secret-key

      AIRFLOW__SMTP__SMTP_HOST: mailpit
      AIRFLOW__SMTP__SMTP_PORT: 1025
      AIRFLOW__SMTP__SMTP_STARTTLS: "False"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP_SMTP_MAIL_FROM: airflow@industrial-iot.local
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: /opt/airflow/simple_auth_manager_passwords.json

    volumes:

      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../.env:/opt/airflow/.env:ro
      - ./simple_auth_manager_passwords.json:/opt/airflow/simple_auth_manager_passwords.json

    command: standalone

networks:
  default:
    name: kafka_default
    external: true